# Generated by Django 4.0.3 on 2022-04-04 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='photo',
            field=models.ImageField(upload_to='photos/', verbose_name='Фото'),
        ),
    ]
